extends: default
rules:
  document-start: disable
  empty-lines:
    max: 1 # Allow one empty line between list items
  braces:
    max-spaces-inside: 1
    level: error
  brackets:
    max-spaces-inside: 1
    level: error
  comments:
    min-spaces-from-content: 1
ignore: |
  .tox/
  .cache/
