# Copied from
# https://github.com/marketplace/actions/pre-commit#using-this-action
# TODO: ignoring file as is for yamlfmt, only because yamlfmt wrecks command
# TODO: prompts
name: pre-commit

on:
  push:
    branches: ["*"]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Install Tflint
        # TODO: cache tflint install
        # yamllint disable rule:line-length
        # prettier-ignore
        run: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
        # yamllint enable rule:line-length

      # Get Date for the Trivy cache key
      - name: Get Date
        id: get-date
        run: |
          echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
        shell: bash

      # Get the latest Trivy version for the Trivy cache key
      - name: Get latest Trivy version
        id: trivy-latest-version
        run: |
          echo "trivy_latest_version=$(curl -s -L -H "Accept: \
          application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/aquasecurity/trivy/releases/latest \
          | jq -r '.tag_name')" >> $GITHUB_OUTPUT
        shell: bash

        # Cache Trivy with its latest version and with the date
        # manual: https://github.com/actions/cache#usage
      - name: Load cached Trivy binary
        id: cache-trivy-binary
        uses: actions/cache@v4
        with:
          path: /usr/local/bin/trivy
          # key: trivy-binary # TODO: This is supposed to be some highly
          # complicated search and cache string
          # yamllint disable rule:line-length
          # prettier-ignore
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ steps.trivy-latest-version.outputs.trivy_latest_version }}
          # yamllint enable rule:line-length

      - name: Install Trivy if it was not found in cache
        if: steps.cache-trivy-binary.outputs.cache-hit != 'true'
        # yamllint disable rule:line-length
        # prettier-ignore
        run: curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin ${{ steps.trivy-latest-version.outputs.trivy_latest_version }}
        # yamllint enable rule:line-length

      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies
      # Install checkov with pip - setup-python claims it is auto caching this
      - run: pip install checkov
        #version: 1.0
      - uses: actions/checkout@v3
      - uses: pre-commit/action@v3.0.1
